import type { Metadata } from 'next';

import { MSWComponent } from '@/src/mocks/MSWComponent';

import Introduction from './_components/Introduction';
import Selector from './_components/Selector';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='ko'>
      <body>
        <MSWComponent>
          <div className='flex h-screen w-screen flex-row items-center justify-center gap-10'>
            <div className='hidden shrink sm:flex'>
              <Introduction />
            </div>
            <div
              id='layout-Root'
              className='relative flex h-full max-h-[950px] min-h-[600px] w-full min-w-[350px] max-w-[450px] shrink-0 flex-col shadow-xl'
            >
              {children}
              <Selector
                items={[
                  { text: 'Item 1' },
                  { text: 'Item 2' },
                  { text: 'Item 3' },
                ]}
                placeholder='테스트 1'
              />
              <Selector
                items={[
                  { text: 'Test 1' },
                  { text: 'Test 2' },
                  { text: 'Test 3' },
                ]}
                placeholder='테스트 2'
              />
            </div>
          </div>
        </MSWComponent>
      </body>
    </html>
  );
};

export default RootLayout;
