name: 'Build Next'

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # setup-node의 pnpm 지원을 위한 Action
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.1
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
